personalwebsite/models.py
from personalwebsite import db
from datetime import datetime


class Myself(db.Model):
    __tablename__ = "me"
    id = db.Column(db.Integer, primary_key=True)
    first_name = db.Column(db.String, nullable=False, default="Kunhee")
    last_name = db.Column(db.String, nullable=False, default="Ha")
    about = db.Column(db.String, nullable=False, default=(
        "Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint"
        " cillum sint consectetur cupidatat."
        ))
    profile_photo = db.Column(db.String, default="default_profile_photo.jpg")
    cv_file = db.Column(db.String)
    contacts = db.relationship("Contact", backref="me")


class Contact(db.Model):
    __tablename__ = "contacts"
    id = db.Column(db.Integer, primary_key=True)
    contact_type = db.Column(db.String, nullable=False)
    link = db.Column(db.String, nullable=False)
    me_id = db.Column(db.Integer, db.ForeignKey("me.id"))


class Skill(db.Model):
    __tablename__ = "skills"
    id = db.Column(db.Integer, primary_key=True)
    skill = db.Column(db.String, nullable=False, default="Arch btw")


class Project(db.Model):
    __tablename__ = "projects"
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String, nullable=False)
    source_code_link = db.Column(db.String, nullable=False)
    webapp = db.Column(db.Boolean, nullable=False, default=False)
    deployed = db.Column(db.Boolean, nullable=False, default=False)
    live_link = db.Column(db.String)
    brief = db.Column(db.String, nullable=False,
                      server_default="a plan for world domination",
                      default="a plan for world domination")
    show_on_main = db.Column(db.Boolean, default=False, server_default="false")


class VisitorInfo(db.Model):
    __tablename__ = "visitors"
    id = db.Column(db.Integer, primary_key=True)
    date_visited = db.Column(db.DateTime, nullable=False,
                             default=datetime.utcnow)
    ip = db.Column(db.String)
    browser = db.Column(db.String(20))
    operating_system = db.Column(db.String(10))
    device_type = db.Column(db.String(10))
    country = db.Column(db.String(5))
    region = db.Column(db.String(50))
    city = db.Column(db.String(50))
    postal = db.Column(db.String(10))
    timezone = db.Column(db.String(20))
    page = db.Column(db.String(10))

personalwebsite/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager
from flask_mail import Mail


db = SQLAlchemy()
migrate = Migrate()
login_manager = LoginManager()
mail = Mail()


def create_app():
    from personalwebsite.config import Config

    app = Flask(__name__)
    app.config.from_object(Config)

    db.init_app(app)
    migrate.init_app(app, db)
#   login_manager.init_app(app)
    mail.init_app(app)

    from personalwebsite.main.routes import main
    from personalwebsite.logger.routes import logger
    from personalwebsite.blog.routes import blog
    app.register_blueprint(main)
    app.register_blueprint(logger)
    app.register_blueprint(blog)

    return app

personalwebsite/blog/routes.py
from flask import Blueprint, render_template
from personalwebsite import db


blog = Blueprint('blog', __name__)


@blog.route('/blog')
def index():
    return render_template('placeholder.html')

personalwebsite/logger/routes.py
from flask import Blueprint, current_app, request, jsonify, Response
from personalwebsite import db
from personalwebsite.models import VisitorInfo


logger = Blueprint('logger', __name__)


@logger.route('/log-visitor', methods=['POST'])
def log_visitor():
    info = request.get_json()
    if info['ipinfo'] == 'true':
        newVisitor = VisitorInfo(
                ip=info['ip'], browser=info['browser'],
                operating_system=info['operatingSystem'],
                device_type=info['deviceType'],
                country=info['country'],
                region=info['region'],
                city=info['city'],
                timezone=info['timezone'],
                page=info['page']
                )
    else:
        newVisitor = VisitorInfo(
                browser=info['browser'],
                operating_system=info['operatingSystem'],
                device_type=info['deviceType'],
                page=info['page']
                )
    db.session.add(newVisitor)
    db.session.commit()

    return Response(status=204)

personalwebsite/main/routes.py
from flask import (
    Blueprint, render_template, current_app, request, jsonify, url_for
        )
from personalwebsite import db, mail
from personalwebsite.models import Myself, Contact, Skill, Project
from flask_mail import Message


main = Blueprint('main', __name__)


@main.route('/')
def index():
    myid = int(current_app.config['MYSELF_ID'])
    me = db.get_or_404(Myself, myid)
    return render_template('index.html', me=me)


@main.route('/about')
def about():
    myid = int(current_app.config['MYSELF_ID'])
    me = db.get_or_404(Myself, myid)
    contacts = db.session.execute(
            db.select(Contact).filter_by(me_id=myid)).scalars().all()
    email = db.session.execute(
            db.select(Contact).filter_by(
                me_id=myid, contact_type="email")).scalar()
    contacts = [contact for contact in contacts
                if contact.contact_type != "email"]
    profile_photo = url_for('static', filename='images/'+me.profile_photo)
    skills = db.session.execute(db.select(Skill)).scalars().all()
    projects = db.session.execute(
            db.select(Project).filter_by(show_on_main=True).limit(4)
            ).scalars().all()

    return render_template('about.html', me=me, email=email,
                           contacts=contacts, projects=projects, skills=skills,
                           profile_photo=profile_photo)


@main.route('/contact', methods=['POST', 'GET'])
def contact():
    if request.method == 'POST':
        # why is this so broken up? because pycodestyle
        sender_name = (
                f"{request.form.get('fname')} {request.form.get('lname')}"
                )
        sender_email = request.form.get('email')
        sender_message = request.form.get('message')
        to_receive = Message(subject='From Website',
                             sender='kunheeha@gmail.com',
                             recipients=['kunheeha@gmail.com'])
        to_send = Message(subject='Message Received',
                          sender='kunheeha@gmail.com',
                          recipients=[sender_email])
        to_receive.html = render_template('email_templates/to_me.html',
                                          sender_name=sender_name,
                                          sender_email=sender_email,
                                          sender_message=sender_message)
        to_send.html = render_template('email_templates/autoresponse.html',
                                       sender_name=sender_name)

        try:
            mail.send(to_receive)
            mail.send(to_send)
            return jsonify(status=True)
        except Exception:
            return jsonify(status=False)


@main.route('/projects')
def projects():
    projects = db.session.execute(db.select(Project)).scalars().all()
    return render_template('projects.html', projects=projects)


# @main.route('/project/<int:project_id>')
# def project_view(project_id):
#     project = db.get_or_404(Project, project_id)
#     return render_template('placeholder.html')

personalwebsite/templates/about.html
{% from 'macros/macros.html' import contact_icon, project_icon %}
{% extends 'base.html' %}

{% block head %}
  <!-- GTM Danny Smith -->
  <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);})(window,document,'script','dataLayer','GTM-NF3Z2GNC');</script>
  <!-- GTM Danny Smith -->
  <link rel="stylesheet" media="screen and (min-width: 700px)" href="{{ url_for('static', filename='css/main.css') }}">
  <link rel="stylesheet" media="screen and (max-width: 699px)" href="{{ url_for('static', filename='css/main_phonescreen.css') }}">
  <title>{{ me.first_name }} {{ me.last_name }}</title>
{% endblock %}

{% block body %}
<!-- GTM Danny Smith -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-NF3Z2GNC" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- GTM Danny Smith -->
<!-- NavBar -->
<nav class="navbar navbar-expand navbar-dark fixed-top" id="mainNav">
  <div class="container">
    <!-- to add something here or not to add, that is the question -->
    <a class="navbar-brand js-scroll-trigger" href="#page-top"><img src="" alt="" /></a>
    <ul class="navbar-nav text-uppercase ml-auto">
      <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#about">About</a></li>
      <li class="nav-item"><a class="nav-link" href="{{ url_for('main.projects') }}">Projects</a></li>
      <li class="nav-item"><a class="nav-link" href="{{ url_for('blog.index') }}">Blog</a></li>
    </ul>
  </div>
</nav>

<!-- Header -->
<header class="about-header">
  <div class="container">
    <div class="row">
      <div class="about-info col-md-6 col-xs-12">
        <h1 data-aos="fade-up" data-aos-duration="800" data-aos-delay="200">{{ me.first_name }} {{ me.last_name }}</h1>
        <h2 data-aos="fade-up" data-aos-duration="800" data-aos-delay="300">Developer</h2>
        <div class="contact-links">
          <ul>
            <li data-aos="fade-up" data-aos-duration="800" data-aos-delay="400"><a>{{ contact_icon(email.contact_type) }}{{ email.link }}</a></li>
          </ul>
          <ul class="social-icon" data-aos="fade-up" data-aos-duration="800" data-aos-delay="500">
            {% for contact in contacts %}
            <li><a target="_blank", href="{{ contact.link }}">{{ contact_icon(contact.contact_type) }}</a></li>
            {% endfor %}
          </ul>
        </div>
      </div>
      <div class="col-md-6 profile-photo">
        <div class="p-img" data-aos="fade" data-aos-duration="1000" data-aos-delay="600">
          <img src="{{ profile_photo }}" alt="">
        </div>
      </div>
    </div>
  </div>
</header>

<!-- About -->
<section class="about-me about-me-section-separator" id="about">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-sm-12">
        <h1 class="h2" data-aos="fade-up" data-aos-duration="800" data-aos-delay="100">About</h1>
        <p data-aos="fade" data-aos-duration="900" data-aos-delay="300">{{ me.about }}</p>
      </div>
      <div class="col-md-1 d-md-block d-sm-none"></div>
      <div class="col-md-5 col-sm-12 about-me-skills">
        <h2 class="h4" data-aos="fade-up" data-aos-duration="800" data-aos-delay="200">my skills</h2>
        <div class="skill-tags">
          <ul data-aos="fade" data-aos-duration="900" data-aos-delay="400">
            {% for skill in skills %}
            <li><span>{{ skill.skill }}</span></li>
            {% endfor %}
          </ul>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- Projects -->
<section class="projects section-separator bg-light">
  <div class="container">
    <div class="text-center">
      <h2 data-aos="fade-up" data-aos-duration="800" data-aos-delay="200">Personal Projects</h2>
    </div>
    <div class="row">
      {% for project in projects %}
      <div class="col-12 col-sm-6 col-xl-3">
        <div class="project-item" data-aos="zoom-in" data-aos-duration="800" data-aos-delay="300">
          <div class="project-item-inner shadow-1 white-bg">
            <div class="project-item-front white-bg">
              {{ project_icon(project.webapp) }}
              <h3>{{ project.name }}</h3>
            </div>
            <div class="project-item-back white-bg">
              <h3 class="h4">{{ project.name }}</h3>
              <p>{{ project.brief }}</p>
              <div class="project-links">
                <span style="float:left;"><a href="{{ project.source_code_link }}" target="_blank">source code</a></span>
                {% if project.webapp and project.deployed %}
                <span style="float:right;"><a href="{{ project.live_link }}" target="_blank">view live</a></span>
                {% endif %}
              </div>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    <div class="project-page-link">
      <a class="internal-links" href="{{ url_for('main.projects') }}" data-aos="fade" data-aos-duration="800" data-aos-delay="600">VIEW ALL</a>
    </div>
  </div> 
</section>
<!-- Contacts -->
<section class="contact section-separator" id="contact">
  <div class="container">
    <div class="text-center">
      <h2 data-aos="fade-up" data-aos-duration="800" data-aos-delay="200" data-aos-once="true">Contact Me</h2>
    </div>
    <div class="map-image image-bg">
      <div class="row justify-content-md-center">
        <div class="col-sm-12 col-md-6 mt-3">
          <div class="formMessages"></div>
          <form class="contact-form" method="POST" action="">
            <div class="form-label-group" data-aos="fade-up" data-aos-duration="800" data-aos-delay="300" data-aos-once="true">
              <input id="inputFname" type="text" name="fname" class="form-control" placeholder="First Name" required>
              <label for="inputFname">First Name</label>
            </div>
            <div class="form-label-group" data-aos="fade-up" data-aos-duration="800" data-aos-delay="400" data-aos-once="true">
              <input id="inputLname" type="text" name="lname" class="form-control" placeholder="Last Name" required>
              <label for="inputLname">Last Name</label>
            </div>
            <div class="form-label-group" data-aos="fade-up" data-aos-duration="800" data-aos-delay="500" data-aos-once="true">
              <input id="inputEmail" type="email" name="email" class="form-control" placeholder="Email" required>
              <label for="inputEmail">Email</label>
            </div>
            <div class="form-label-group" data-aos="fade-up" data-aos-duration="800" data-aos-delay="600" data-aos-once="true">
              <textarea id="inputMessage" class="form-control" name="message" placeholder="Message" rows="6" required></textarea>
              <label for="inputMessage">Message</label>
            </div>
            <hr>
            <div class="card">
              <button type="submit" class="btn btn-block btn-dark" data-aos="fade-up" data-aos-duration="800" data-aos-delay="700" data-aos-once="true">Send Message</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

{% block scripts %}
  <script src="{{ url_for('static', filename='js/email.js') }}"></script>
  <script src="{{ url_for('static', filename='js/scrolling.js') }}"></script>
  <script type="module" src="{{ url_for('static', filename='js/logvisitor.js') }}"></script>
{% endblock scripts %}

personalwebsite/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Meta tags -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Hi mom">
    <meta name="author" content="Kunhee Ha">

    <!-- Google Font Roboto -->
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Libre+Baskerville">
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Fira+Sans">
    <!-- npm packages -->

    <!-- Bootstrap -->
    <link rel="stylesheet"  href="{{ url_for('static', filename='node_modules/bootstrap/dist/css/bootstrap.min.css') }}">
    <!-- FontAwesome -->
    <link rel="stylesheet" href="{{ url_for('static', filename='node_modules/@fortawesome/fontawesome-free/css/fontawesome.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='node_modules/@fortawesome/fontawesome-free/css/brands.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='node_modules/@fortawesome/fontawesome-free/css/solid.css') }}">
    <!-- Animate.css -->
    <link rel="stylesheet" href="{{ url_for('static', filename='node_modules/animate.css/animate.css') }}">
    <!-- AOS css -->
    <link rel="stylesheet" href="{{ url_for('static', filename='node_modules/aos/dist/aos.css') }}">

    <!-- My stuff -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css') }}">

  {% block head %}{% endblock %}
  </head>
  <body>
    {% block body %}{% endblock %}

    <!-- Footer -->
    <footer class="footer py-4 bg-light">
      <div class="container">
        © Kunhee Ha
      </div>
    </footer>

  
    <!-- Utils -->
    <script type="module" scr="{{ url_for('static', filename='js/utils.js') }}"></script>
    <!-- Bootstrap -->
    <script src="{{ url_for('static', filename='node_modules/bootstrap/dist/js/bootstrap.bundle.min.js') }}"></script>
    <!-- AOS -->
    <script src="{{ url_for('static', filename='node_modules/aos/dist/aos.js') }}"></script>
    <script>
      AOS.init();
    </script>
    <!-- My Stuff -->
    {% block scripts %}{% endblock %}
  </body>
</html>

personalwebsite/templates/email_templates/autoresponse.html
<!DOCTYPE html>
<html>
<head>
	<title>Message Received</title>
</head>
<body>
	<p>Dear {{ sender_name }},</p>
	<br>

	<p>Your message has been received and I will respond to you shortly.</p>
	<br>

	<p>Regards,</p>
	<p>Kunhee Ha</p>
</body>
</html>

personalwebsite/templates/email_templates/to_me.html
<!DOCTYPE html>
<html>
<head>
	<title>Message from Personal Website</title>
</head>
<body>
	<p>Sender: {{ sender_name }}</p>
	<p>Email: {{ sender_email }}</p>
	<br>
	<p>{{ sender_message }}</p>
</body>
</html>

personalwebsite/templates/index.html
{% extends 'base.html' %}
{% block head %}
  <link rel="stylesheet" media="screen and (min-width: 700px)" href="{{ url_for('static', filename='css/main.css') }}">
  <link rel="stylesheet" media="screen and (max-width: 699px)" href="{{ url_for('static', filename='css/main_phonescreen.css') }}">
  <title>{{ me.first_name }} {{ me.last_name }}</title>

{% endblock %}
{% block body %}
  <!-- NavBar -->
  <nav class="navbar navbar-expand navbar-dark fixed-top" id="mainNav">
    <div class="container">
      <!-- to add something here or not to add, that is the question -->
      <a class="navbar-brand js-scroll-trigger" href="#page-top"><img src="" alt="" /></a>
      <ul class="navbar-nav text-uppercase ml-auto">
        <li class="nav-item"><a class="nav-link" href="{{ url_for('main.about') }}">About</a></li>
        <li class="nav-item"><a class="nav-link" href="{{ url_for('main.projects') }}">Projects</a></li>
        <li class="nav-item"><a class="nav-link" href="{{ url_for('blog.index') }}">Blog</a></li>
      </ul>
    </div>
  </nav>

  <section class="fullscreen landing-page">
    <div class="container">
      <h1>About you</h1>
      <div class="about-user-text" id="pseudo-loading"></div>
      <div class="about-user-text"id="introduction-text"></div>
      <div class="about-user-text"id="userinfo-text"></div>
      <div class="about-me-link">
        <a id="about-me-link" href="{{ url_for('main.about') }}">About me</a>
      </div>
    </div>
  </section>

{% endblock %}


{% block scripts %}
  <script type="module" src="{{ url_for('static', filename='js/aboutyou.js') }}"></script>
  <script type="module" src="{{ url_for('static', filename='js/logvisitor.js') }}"></script>
{% endblock scripts %}

personalwebsite/templates/macros/macros.html
{% macro contact_icon(type) -%}
{% if type == "github" %}
  <i class="fa-brands fa-github"></i>
{% elif type == "linkedin" %}
  <i class="fa-brands fa-linkedin"></i>
{% elif type == "stackoverflow" %}
  <i class="fa-brands fa-stack-overflow"></i>
{% elif type == "email" %}
  <i class="fa-solid fa-envelope"></i>
{% else %}
  <i class="fa-solid fa-link"></i>
{% endif %}
{%- endmacro %}

{% macro project_icon(webapp) -%}
{% if webapp %}
  <i class="fa-solid fa-code"></i>
{% else %}
  <i class="fa-regular fa-object-ungroup"></i>
{% endif %}
{%- endmacro %}

personalwebsite/templates/placeholder.html
{% extends 'base.html' %}
{% block head %}
  <link rel="stylesheet" href="{{ url_for('static', filename='css/placeholder.css') }}">
  <title>wow so empty</title>
{% endblock %}

{% block body %}
<!-- NavBar -->
<nav class="navbar navbar-expand navbar-dark fixed-top" id="mainNav">
  <div class="container">
    <!-- to add something here or not to add, that is the question -->
    <a class="navbar-brand js-scroll-trigger" href="#page-top"><img src="" alt="" /></a>
    <ul class="navbar-nav text-uppercase ml-auto">
      <li class="nav-item"><a class="nav-link" href="{{ url_for('main.about') }}">About</a></li>
      <li class="nav-item"><a class="nav-link" href="{{ url_for('main.projects') }}">Projects</a></li>
      <li class="nav-item"><a class="nav-link" href="{{ url_for('blog.index') }}">Blog</a></li>
    </ul>
  </div>
</nav>

<section class="fullscreen landing-page">
  <div class="container">
    <h2>haven't completed making this page yet... come back later</h2>
    <div class="sendaway">
      <a href="https://motherfuckingwebsite.com/" target="_blank">Why is your website so boring?</a>
    </div>
  </div>
</section>
{% endblock %}

personalwebsite/templates/projects.html
{% extends 'base.html' %}

{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/projects.css') }}">
  <title>Projects</title>
{% endblock head %}

{% block body %}
<!-- NavBar -->
<nav class="navbar navbar-shrink navbar-expand navbar-dark fixed-top" id="mainNav">
  <div class="container">
    <!-- to add something here or not to add, that is the question -->
    <a class="navbar-brand js-scroll-trigger" href="#page-top"><img src="" alt="" /></a>
    <ul class="navbar-nav text-uppercase ml-auto">
      <li class="nav-item"><a class="nav-link" href="{{ url_for('main.about') }}">About</a></li>
      <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#projects">Projects</a></li>
      <li class="nav-item"><a class="nav-link" href="{{ url_for('blog.index') }}">Blog</a></li>
    </ul>
  </div>
</nav>

<!-- Header -->
<header class="projects-header">
  <div class="container">
    <h1 data-aos="fade-right" data-aos-duration="800" data-aos-delay="200">personal projects</h1>
    <p data-aos="fade-right" data-aos-duration="800" data-aos-delay="300">noun: /ˈpɜːrsənəl ˈprɒdʒɛkts/</p>
    <h3 data-aos="fade-right" data-aos-duration="800" data-aos-delay="400">a collection of random things I made in my spare time</h3>
  </div>
</header>

<!-- Main -->
<section class="projects-main bg-light" id="projects">
  <div class="container">
    <div class="row row-cols-1 row-cols-md-3">
      {% for project in projects %}
      <div class="col mb-5 mr-5" data-aos="zoom-in" data-aos-duration="800" data-aos-delay="{{ project.id }}00">
        {% if project.deployed %}
        <a href="{{ project.live_link }}" target="_blank">
        {% else %}
        <a href="{{ project.source_code_link }}" target="_blank">
        {% endif  %}
          <div class="project-item white-bg">
            <h4>{{ project.name }}</h4>
            <p>{{ project.brief }}</p>
          </div>
        </a>
      </div>
      {% endfor %}
    </div>
  </div>
</section>

{% endblock body %}

{% block scripts %}
<script>
document.querySelectorAll('a.js-scroll-trigger[href*="#"]:not([href="#"])').forEach(link => {
  link.onclick = function() {
    if (location.pathname.replace(/^\//, "") == link.pathname.replace(/^\//, "")) {
      document.querySelector(link.hash).scrollIntoView({ behavior: "smooth" });
      return false;
    }
  }
});
</script>
{% endblock scripts %}